#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"; PORT="$2"; IP="$3"

dokku monit:build-control $APP $PORT $IP
root@devweb1:/var/lib/dokku/plugins/monit# cat post-domains-update
#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

APP="$1"

dokku monit:build-control $APP
